### PR TITLE
Add support for Apple Silicon

### LINKED ISSUE #111: Port to Apple Silicon
This may be along shot, but any chance this could be ported to M1 Mac? Just getting ideas how feasible this is and if it needs to be forked separately.

### PR DESCRIPTION
**Pull request by hosterholz**
Resolves #111

### CODE REVIEW

**Comment by MAN-AT-ARMS** [comment]
Just out of curiosity...do you have this running on M1? If so, were any other changes needed?

**Comment by hosterholz** [comment]
It's running on the MacBook Air (M1, 2020).
I installed the latest SDL2.framework in /Library/Framework and installed `openal-soft`, `opus` and `opusfile` via homebrew.

Here's my Makefile.local
```Makefile
ifeq ($(ARCH),arm64)
  USE_LOCAL_HEADERS=0
  CFLAGS+=-I/opt/homebrew/opt/openal-soft/include
  CFLAGS+=-I/opt/homebrew/opt/opus/include
  CFLAGS+=-I/opt/homebrew/opt/opusfile/include
  CFLAGS+=-F/Library/Frameworks
endif
```

**Comment by halpz** [comment]
with your branch, I've been getting this issue building on M1 macbook pro:

`Undefined symbols for architecture arm64:
  "_SDL_ClearQueuedAudio", referenced from:
      _SNDDMA_StartCapture in sdl_snd.o
  "_SDL_CloseAudioDevice", referenced from:
Undefined symbols for architecture arm64:
  "_SDL_CreateWindow", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _SNDDMA_Shutdown in sdl_snd.o
  "_SDL_DestroyWindow", referenced from:
  "_SDL_DequeueAudio", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _SNDDMA_Capture in sdl_snd.o
  "_SDL_FreeSurface", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GameControllerClose", referenced from:
  "_SDL_GL_CreateContext", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _IN_InitJoystick in sdl_input.o
      _IN_Shutdown in sdl_input.o
      _IN_Restart in sdl_input.o
  "_SDL_GL_DeleteContext", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GL_ExtensionSupported", referenced from:
      _GLimp_Init in sdl_glimp.o
  "_SDL_GameControllerEventState", referenced from:
  "_SDL_GL_GetAttribute", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _IN_InitJoystick in sdl_input.o
  "_SDL_GL_GetProcAddress", referenced from:
      _GLimp_Init in sdl_glimp.o
      _GLimp_GetProcAddresses in sdl_glimp.o
  "_SDL_GameControllerGetAxis", referenced from:
  "_SDL_GL_SetAttribute", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _IN_Frame in sdl_input.o
  "_SDL_GL_SetSwapInterval", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GameControllerGetButton", referenced from:
  "_SDL_GL_SwapWindow", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _GLimp_EndFrame in sdl_glimp.o
      _IN_Frame in sdl_input.o
  "_SDL_GetCurrentVideoDriver", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GameControllerOpen", referenced from:
  "_SDL_GetDesktopDisplayMode", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _IN_InitJoystick in sdl_input.o
  "_SDL_GetDisplayMode", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GameControllerUpdate", referenced from:
  "_SDL_GetError", referenced from:
      _GLimp_SetGamma in sdl_gamma.o
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _IN_Frame in sdl_input.o
  "_SDL_GetNumDisplayModes", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GetClipboardText", referenced from:
  "_SDL_GetWindowDisplayIndex", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _Sys_GetClipboardData in sys_main.o
  "_SDL_GetWindowDisplayMode", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GetCurrentAudioDriver", referenced from:
  "_SDL_GetWindowFlags", referenced from:
      _GLimp_EndFrame in sdl_glimp.o
      _SNDDMA_Init in sdl_snd.o
  "_SDL_GetWindowPosition", referenced from:
      _GLimp_Shutdown in sdl_glimp.o
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GetError", referenced from:
      _CL_InitRef in cl_main.o
  "_SDL_Init", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _IN_Frame in sdl_input.o
  "_SDL_MinimizeWindow", referenced from:
      _IN_DeactivateMouse in sdl_input.o
      _IN_InitJoystick in sdl_input.o
      _SNDDMA_Init in sdl_snd.o
      _Sys_LoadGameDll in sys_main.o
      _GLimp_Minimize in sdl_glimp.o
  "_SDL_QuitSubSystem", referenced from:
      _GLimp_Shutdown in sdl_glimp.o
  "_SDL_GetKeyName", referenced from:
  "_SDL_SetWindowBrightness", referenced from:
      _IN_TranslateSDLToQ3Key in sdl_input.o
      _GLimp_Init in sdl_glimp.o
  "_SDL_SetWindowDisplayMode", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GetQueuedAudioSize", referenced from:
  "_SDL_SetWindowGammaRamp", referenced from:
      _GLimp_SetGamma in sdl_gamma.o
      _SNDDMA_AvailableCaptureSamples in sdl_snd.o
  "_SDL_SetWindowIcon", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GetScancodeName", referenced from:
  "_SDL_WasInit", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _IN_TranslateSDLToQ3Key in sdl_input.o
  "_SDL_calloc", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
  "_SDL_GetVersion", referenced from:
  "_SDL_free", referenced from:
      _GLimp_StartDriverAndSetMode in sdl_glimp.o
      _main in sys_main.o
  "_SDL_GetWindowFlags", referenced from:
      _IN_Frame in sdl_input.o
      _IN_DeactivateMouse in sdl_input.o
      _IN_Init in sdl_input.o
ld: symbol(s) not found for architecture arm64
  "_SDL_Has3DNow", referenced from:
      _Sys_GetProcessorFeatures in sys_main.o
REF_STR code/rend2/glsl/depthblur_fp.glsl
  "_SDL_HasAltiVec", referenced from:
      _Sys_GetProcessorFeatures in sys_main.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
  "_SDL_HasMMX", referenced from:
      _Sys_GetProcessorFeatures in sys_main.o
  "_SDL_HasRDTSC", referenced from:
make[2]: *** [build/release-darwin-arm64/renderer_mp_opengl1_arm64.dylib] Error 1
make[2]: *** Waiting for unfinished jobs....
      _Sys_GetProcessorFeatures in sys_main.o
  "_SDL_HasSSE", referenced from:
      _Sys_GetProcessorFeatures in sys_main.o
  "_SDL_HasSSE2", referenced from:
      _Sys_GetProcessorFeatures in sys_main.o
  "_SDL_Init", referenced from:
      _IN_InitJoystick in sdl_input.o
      _SNDDMA_Init in sdl_snd.o
  "_SDL_IsGameController", referenced from:
      _IN_InitJoystick in sdl_input.o
  "_SDL_JoystickClose", referenced from:
      _IN_InitJoystick in sdl_input.o
      _IN_Shutdown in sdl_input.o
      _IN_Restart in sdl_input.o
  "_SDL_JoystickEventState", referenced from:
      _IN_InitJoystick in sdl_input.o
  "_SDL_JoystickGetAxis", referenced from:
      _IN_Frame in sdl_input.o
  "_SDL_JoystickGetBall", referenced from:
      _IN_Frame in sdl_input.o
  "_SDL_JoystickGetButton", referenced from:
      _IN_Frame in sdl_input.o
  "_SDL_JoystickGetHat", referenced from:
      _IN_Frame in sdl_input.o
  "_SDL_JoystickNameForIndex", referenced from:
      _IN_InitJoystick in sdl_input.o
  "_SDL_JoystickNumAxes", referenced from:
      _IN_Frame in sdl_input.o
      _IN_InitJoystick in sdl_input.o
  "_SDL_JoystickNumBalls", referenced from:
      _IN_Frame in sdl_input.o
      _IN_InitJoystick in sdl_input.o
  "_SDL_JoystickNumButtons", referenced from:
      _IN_Frame in sdl_input.o
      _IN_InitJoystick in sdl_input.o
  "_SDL_JoystickNumHats", referenced from:
      _IN_Frame in sdl_input.o
      _IN_InitJoystick in sdl_input.o
  "_SDL_JoystickOpen", referenced from:
      _IN_InitJoystick in sdl_input.o
  "_SDL_JoystickUpdate", referenced from:
      _IN_Frame in sdl_input.o
  "_SDL_LoadFunction", referenced from:
      _CL_InitRef in cl_main.o
      _QAL_Init in qal.o
      _CL_cURL_Init in cl_curl.o
      _Sys_LoadGameDll in sys_main.o
  "_SDL_LoadObject", referenced from:
      _Sys_LoadDll in sys_main.o
      _Sys_LoadGameDll in sys_main.o
  "_SDL_LockAudioDevice", referenced from:
      _SNDDMA_BeginPainting in sdl_snd.o
  "_SDL_NumJoysticks", referenced from:
      _IN_InitJoystick in sdl_input.o
  "_SDL_OpenAudioDevice", referenced from:
      _SNDDMA_Init in sdl_snd.o
  "_SDL_PauseAudioDevice", referenced from:
      _SNDDMA_Init in sdl_snd.o
      _SNDDMA_StartCapture in sdl_snd.o
      _SNDDMA_StopCapture in sdl_snd.o
  "_SDL_PeepEvents", referenced from:
      _IN_Frame in sdl_input.o
      _IN_DeactivateMouse in sdl_input.o
  "_SDL_PollEvent", referenced from:
      _IN_Frame in sdl_input.o
  "_SDL_PumpEvents", referenced from:
      _IN_Frame in sdl_input.o
      _IN_DeactivateMouse in sdl_input.o
  "_SDL_Quit", referenced from:
      _Sys_Exit in sys_main.o
  "_SDL_QuitSubSystem", referenced from:
      _IN_InitJoystick in sdl_input.o
      _IN_Shutdown in sdl_input.o
      _IN_Restart in sdl_input.o
      _SNDDMA_Init in sdl_snd.o
      _SNDDMA_Shutdown in sdl_snd.o
  "_SDL_SetRelativeMouseMode", referenced from:
      _IN_Frame in sdl_input.o
      _IN_DeactivateMouse in sdl_input.o
  "_SDL_SetWindowGrab", referenced from:
      _IN_Frame in sdl_input.o
      _IN_DeactivateMouse in sdl_input.o
  "_SDL_ShowCursor", referenced from:
      _IN_DeactivateMouse in sdl_input.o
  "_SDL_StartTextInput", referenced from:
      _IN_Init in sdl_input.o
  "_SDL_StopTextInput", referenced from:
      _IN_Shutdown in sdl_input.o
  "_SDL_UnloadObject", referenced from:
      _CL_ShutdownAll in cl_main.o
      _CL_ShutdownRef in cl_main.o
      _CL_Vid_Restart_f in cl_main.o
      _QAL_Shutdown in qal.o
      _CL_cURL_Shutdown in cl_curl.o
      _Sys_UnloadDll in sys_main.o
      _Sys_LoadGameDll in sys_main.o
      ...
  "_SDL_UnlockAudioDevice", referenced from:
      _SNDDMA_Submit in sdl_snd.o
  "_SDL_WarpMouseInWindow", referenced from:
      _IN_DeactivateMouse in sdl_input.o
  "_SDL_WasInit", referenced from:
      _IN_Frame in sdl_input.o
      _IN_DeactivateMouse in sdl_input.o
      _IN_Init in sdl_input.o
      _IN_InitJoystick in sdl_input.o
      _IN_Shutdown in sdl_input.o
      _IN_Restart in sdl_input.o
      _Sys_In_Restart_f in sys_main.o
      ...
  "_SDL_free", referenced from:
      _Sys_GetClipboardData in sys_main.o
  "_SDL_memset", referenced from:
      _SNDDMA_Init in sdl_snd.o
      _SNDDMA_Capture in sdl_snd.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [build/release-darwin-arm64/iowolfmp.arm64] Error 1
rm build/release-darwin-arm64/rend2/glsl/depthblur_fp.c build/release-darwin-arm64/rend2/glsl/calclevels4x_fp.c build/release-darwin-arm64/rend2/glsl/calclevels4x_vp.c build/release-darwin-arm64/rend2/glsl/bokeh_fp.c build/release-darwin-arm64/rend2/glsl/bokeh_vp.c
make[1]: *** [targets] Error 2
make: *** [release] Error 2`

**Comment by hosterholz** [comment]
I did not update the included dylibs in the repository, because I did not want to break ppc builds. These cannot be used to link on arm64. Please try building without using local libs like I described in the comment above.

**Comment by halpz** [comment]
> I did not update the included dylibs in the repository, because I did not want to break ppc builds. These cannot be used to link on arm64. Please try building without using local libs like I described in the comment above.

Ah ok - where does the makefile.local go ?

**Comment by halpz** [comment]
sorry figured it out - goes in the same directory as the Makefile, 
seems to be working now!

thanks

**Pull request merged**
