### PR TITLE
SP: Some console-related issues fixes

### PR DESCRIPTION
**Pull request by WSSDude**
- prevent opening console during cinematics
- pause the game when console is opened
- ignore mouse when console is opened
- block menu when menu and console is opened
- prevent opening menu when console is opened
- prevent closing menu with console opened

### CODE REVIEW

**Comment by WSSDude** [comment]
Should be final for now so if you want to merge, you are free to go.
Everything tested on my PC, fully working.

**Comment by zturtleman** [comment]
The console is a developer tool. It should not pause the game or be prevented from opening during cinematics.

**Comment by WSSDude** [comment]
This is behaviour of vanilla. Its up for debate I guess, but this is definitely more vanilla friendly.

**Comment by zturtleman** [comment]
That's odd but guess it's fine then. :man_shrugging:

**Comment by MAN-AT-ARMS** [comment]
I don't believe this is vanilla behavior. It pauses on Menu open. In any case, it's not the desired behavior.

**Comment by WSSDude** [comment]
Ok, actually checked vanilla and it is indeed behaving the way you stated.
I though I was playing vanilla but I launched Knightmare's version instead... 

Dunno if this should be closed than or not but confirming now that it is not indeed vanilla and thus can now be think of more of as enhancement.

**Comment by MAN-AT-ARMS** [comment]
Thanks for checking back on the vanilla behavior. I never recalled it being that way and I was starting to question myself.

**Pull request closed without merging**
