### PR TITLE
Add Quick Start Guide to README.md

### PR DESCRIPTION
**Pull request by MasterO2**
The Readme currently does not specify what files are needed to run Return to Castle Wolfenstein's single player campaign and where those files need to be installed.  

@MAN-AT-ARMS

### CODE REVIEW

**Comment by MAN-AT-ARMS** [comment]
This is actually not quite correct. sp_pak3.pk3 is language specific and there are separate zip file for those. They need to match the installed language version. Also, there is no mention of copying the MP related pak's into the main folder as well.

**Comment by MasterO2** [comment]
> This is actually not quite correct. sp_pak3.pk3 is language specific and there are separate zip file for those. They need to match the installed language version. Also, there is no mention of copying the MP related pak's into the main folder as well.

@MAN-AT-ARMS 

I've made this pull request editable, so if you or any of the other maintainers want to add that information, you can do that as well.  The Quick Start guide above was written based on the English language edition of RTCW as sold on GOG.com, which is why I did not mention the other language packs.

**Comment by MasterO2** [comment]
Have I added everything necessary for this pull request, @MAN-AT-ARMS ?

**Comment by MAN-AT-ARMS** [comment]
Thank you

**Pull request merged**
