### PR TITLE
BOTH: Various small fixes

### PR DESCRIPTION
**Pull request by WSSDude**
- fixed many wrong token checks
- fixed "don't open menu during load" fix (originally one check omitted)
- removed -ffast-math compile option from Release
- added -ggdb to copmile options of Debug (otherwise it is missing symbols for debugging with GDB)
- added code for striping all symbols from Release targets

### CODE REVIEW

**Comment by WSSDude** [comment]
Don't merge yet (if you want to...)
I'm currently going through all token checks and filling the rest with pointer check where it has meaning (which is like 90% of the time...)

**Comment by WSSDude** [comment]
I didn't realize at first that there are COM_Parse and COM_ParseExt functions which behave differently...
Going to need to take it in mind...

**Comment by WSSDude** [comment]
- fixed all token checks in MP and SP that could lead to null dereferencing

Should be final for now so if you want to merge, you are free to go.
Everything tested on my PC, fully working.

**Comment by KuehnhammerTobias** [comment]
Didn't part of this revert: 4aad7c6 ?

**Comment by WSSDude** [comment]
If then not all.

As I wrote, there are two functions - Com_Parse and Com_ParseExt.

Some Com_Parse are forwards for Com_ParseExt, which behaves differently from regular Com_Parse that is used in some places and can return NULL, thus check should be in place for it.

**Comment by zturtleman** [comment]
Fast math may be required to match the behavior of the original RTCW executables which is important for collision in multiplayer.

Instead of using strip command after compiling binary, pass "-s" to CXX when linking binary.

COM_Parse() and COM_ParseExt() functions always return `com_token` which is never NULL.

UI_Argv returns a pointer to a single static character array. Cannot pass multiple arguments to function directly from UI_Argv. Now all arguments for trap_R_RemapShader will incorrectly be the same command argument (which command argument is undefined).
SP/code/ui/ui_atoms.c:
```
	if ( Q_stricmp( cmd, "remapShader" ) == 0 ) {
-		if ( trap_Argc() == 4 ) {
-			char shader1[MAX_QPATH];
-			char shader2[MAX_QPATH];
-			char shader3[MAX_QPATH];
-			Q_strncpyz( shader1, UI_Argv( 1 ), sizeof( shader1 ) );
-			Q_strncpyz( shader2, UI_Argv( 2 ), sizeof( shader2 ) );
-			Q_strncpyz(shader3, UI_Argv(3), sizeof(shader3));
-			
-			trap_R_RemapShader(shader1, shader2, shader3);
+		if ( trap_Argc() == 4 ) {			
+			trap_R_RemapShader( UI_Argv( 1 ), UI_Argv( 2 ), UI_Argv( 3 ) );
			return qtrue;
		}
	}
```

CG_Argv is the same as UI_Argv. Cannot pass multiple arguments to function directly from CG_Argv.
SP/code/cgame/cg_servercmds.c:
```
+		trap_R_RemapShader( CG_Argv( 1 ), CG_Argv( 2 ), CG_Argv( 3 ) );
...
+		CG_ObjectivePrint( CG_Argv( 2 ), SMALLCHAR_WIDTH, atoi( CG_Argv( 1 ) ) );
```

Initialized shorts are not supported by QVMs.
SP/code/cgame/cg_effects.c
```
-unsigned int randtable[NUMRANDTABLE] =
+unsigned short randtable[NUMRANDTABLE] =
{
	0x0000, 0x1021, 0x2042, 0x3063, 0x4084, 0x50a5, 0x60c6, 0x70e7,
	0x8108, 0x9129, 0xa14a, 0xb16b, 0xc18c, 0xd1ad, 0xe1ce, 0xf1ef,
```

**Comment by WSSDude** [comment]
Are you sure about that Com_Parse()? 
I'm sure I found at least one implementation that returned NULL directly and thus is unsafe to use this way. In all places in code where I put that, this function/s are used so it should be possible to get null dereference error.

Regarding strip - I didn't knew where to put -s switch correctly, that's why I opted for this way of doing things.
It is quite complex Makefile so... Anyway, fixing that for sure.

Others I take into account and will change.
If you can look into that Com_Parse() thing once more, would be great.
It is possible that some incorrect definition was linked to it by IntelliSense (I'm using VS Code as editor for this) so I can remove them as well. But as I said, it linked to those definitions in those cases (as you can see, not all Com_Parse() results are being checked as they behave the way you said, only those affected).

**Comment by WSSDude** [comment]
Just one funny thing - how it comes that game works without any apparent issues when I'm now wrongly parsing arguments? (the UI_Argv(),...)

Shouldn't it had some visible effects or am I just blind?

**Comment by WSSDude** [comment]
Oh, one more thing (sorry for spamming comments...)

I linked -ffast-math to hit detection issues which I didn't have in Debug mod at all.
Also, jumping behaved weirdly with it (taking damage when I shouldn't), mouse stuttered,...

This single compile flag removal fixes many issues for me so I don't know...

I'll left it there for now, fix the rest and wait for your answers to some of my questions @zturtleman (tagging you just to be sure you see al this)

**Comment by zturtleman** [comment]
I think remapShader UI command is a development command that is not directly used by the game. If you replace `trap_R_RemapShader(...)` with `Com_Printf( "%s %s %s\n", UI_Argv(1), UI_Argv(2), UI_Argv(3) );` and in the console manually run `remapShader totally different arguments` you should see the issue.

COM_Parse() and COM_ParseExt() are in code/qcommon/q_shared.c and (for splines library) code/splines/q_shared.cpp. There is also Com_Parse() and Com_ParseExt() (different case) in code/splines/q_parse.cpp. As far as I can see none of these can return NULL. If you find an implementation that returns NULL, it should be fixed to return an empty string instead of adding NULL token checks everywhere.

**Comment by MAN-AT-ARMS** [comment]
Thanks, but I'm not merging this. Need to do proper pull requests for seperate issues and without name tags all over. Feel free to discuss the issues here though.

**Comment by WSSDude** [comment]
I didn't want to have 10 branches for one-liners mostly but ok, splitting this in a minute.

**Comment by MAN-AT-ARMS** [comment]
Thanks, It's a little difficult to test / cherrypick fixes individually when they're all clumped together in one patch.

**Comment by WSSDude** [comment]
Yeah, understand you fully, was just lazy I guess :P Pushing them now one-by-one.

**Comment by WSSDude** [comment]
Split into separate pull-requests
#56 #57 #58 #59 #60 #61 #62

**Comment by WSSDude** [comment]
Closing this - no longer needed.

**Pull request closed without merging**
